#!/usr/bin/env python
#-*- coding: utf-8 -*-

from mysql.connector import connect
import json
from datetime import datetime
from optparse import OptionParser

table    = 'est29'
filename = '147858674500006b-20170309.txt'

def dt(ts_msec):
    return datetime.fromtimestamp(ts_msec / 1000.0)

{
        "body": {
            "timestamp": 1513785661897, 
            "conn_id": 1126334260, 
            "reason": "en.sent.score, 60010", 
            "version": 17111296
            }, 
        "sip": "120.26.40.239", 
        "uid": "ulearning-ios", 
        "ts": 1513785661628, 
        "cip": "117.136.72.160", 
        "applicationId": "144152217200000b", 
        "dbTime": 1513785661926
}

def parse_value(string):
    o   = json.loads(string)

    cts = o['body']['timestamp'] if o['body'].has_key('timestamp') else 0
    conn_id = o['body']['conn_id'] if o['body'].has_key('conn_id') else 0
    ver = o['body']['version'] if o['body'].has_key('version') else 0
    if o['body'].has_key('conn_id'):
        reason = o['body']['reason']
        coretype, errno = reason.split(', ')
    else:
        coretype, errno = 'unknown', '0'

    return conn_id, coretype, errno, o['sip'], o['uid'], o['cip'], o['applicationId'], dt(cts), dt(o['ts']), dt(o['dbTime']), ver

def main():
    parse_args()

    sql = ("INSERT INTO " + table + " "
        "(conn_id,coretype,errno,sip,uid,cip,appkey,cts,sts,dbts,version) "
        "VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)")

    conn = connect(host='10.0.200.15', user='root', password='root', db='donli')
    cursor = conn.cursor()

    cursor.execute("DELETE FROM " + table + ";")
    conn.commit()

    i = 1
    lines = []

    with open(filename) as f:
        for line in f:
            if line.startswith('{'):
                try:
                    lines.append(parse_value(line))

                    if len(lines) > 1000:
                        cursor.executemany(sql, lines)
                        conn.commit()

                        del lines[:]

                    print '[ I ]: inserted rows ', i
                    i += 1
                except Exception, e:
                    raise
                    print '[ E ]:', e
                    continue

        if len(lines) > 0:
            cursor.executemany(sql, lines)
            conn.commit()

    conn.close()

    print '[ I ]: Table:', table, 'Log File:', filename

def parse_args():
    global table, filename

    MSG_USAGE = './import -t <table> -f <log file>'
    parser = OptionParser(MSG_USAGE)
    parser.add_option('-t', '--table', dest='table', default=table,
                      help="""table name. example: -t est29""")
    parser.add_option('-f', '--file', dest='filename', default=filename,
                      help="""used to specify logfile. example:""" + filename)

    (options, args) = parser.parse_args()

    table    = options.table
    filename = options.filename

    print '[ I ]: Table:', table, 'Log File:', filename

if __name__ == "__main__": main()
